javascripts:
  art-dev:
    - 'artJs/Initialize'
    - 'artJs/utils/Log'
    - 'artJs/utils/ObjectUtils'
    - 'artJs/utils/ArrayUtils'
    - 'artJs/utils/Class'
    - 'artJs/events/Delegate'
    - 'artJs/utils/MathUtils'
    - 'artJs/utils/StringUtils'
    - 'artJs/utils/DateUtils'
    - 'artJs/utils/EventUtils'
    - 'artJs/utils/ElementUtils'
    - 'artJs/utils/Toggler'
    - 'artJs/utils/ClassToggler'
    - 'artJs/module/Locator'
    - 'artJs/events/DelegateCollection' 
    - 'artJs/events/CustomEvent'
    - 'artJs/math/Point'
    - 'artJs/math/Rectangle'
    - 'artJs/dom/Component'
    - 'artJs/dom/ElementBuilder'
    - 'artJs/dom/Selector'
    - 'artJs/dom/Signature'
    - 'artJs/net/Ajax'
    - 'artJs/data/List'
    - 'artJs/data/Model'
    - 'artJs/data/Queue'
    - 'artJs/events/Clock'
    - 'artJs/events/Broadcaster'
    - 'artJs/events/ElementEvent'
    - 'artJs/events/Timeline'
    - 'artJs/events/Timeout'
    - 'artJs/transition/Base'
    - 'artJs/transition/Blind'
    - 'artJs/transition/Fade'
    - 'artJs/spec/matchers/Base'
    - 'artJs/spec/matchers/A'
    - 'artJs/spec/matchers/Eq'
    - 'artJs/spec/matchers/False'
    - 'artJs/spec/matchers/Null'
    - 'artJs/spec/matchers/Receive'
    - 'artJs/spec/matchers/True'
    - 'artJs/spec/Actual'
    - 'artJs/spec/Definition'
    - 'artJs/spec/Mock'
    - 'artJs/spec/Node'
    - 'artJs/spec/Receiver'
    - 'artJs/spec/Result'
    - 'artJs/spec/Runner'
    - 'artJs/spec/Subject'
    - 'artJs/spec/Core'
    - 'artJs/template/Base'
    - 'artJs/template/Helpers'
    - 'artJs/template/Library'
    - 'artJs/ui/DatePicker'
    - 'artJs/ui/ElementInspector'
    - 'artJs/ui/Select'
    - 'artJs/ui/Tree'
    - 'artJs/Finalize'
  docs-dev: 
    - 'Docs'
    - 'art/model/Member'
    - 'art/DB'
    - 'art/Helpers'
    - 'art/component/Sidebar'
    - 'art/component/Content'
    - 'art/component/Member'
  main-dev: 'Main'
stylesheets:
  shared-dev: 'css/shared'
  docs-dev: 'css/docs'
  main-dev: 'css/main'
  artjs-dev: 'css/artjs'

