javascripts:
  art-dev:
    - 'artJs/Initialize'
    - 'artJs/utils/Log'
    - 'artJs/utils/Array'
    - 'artJs/utils/Object'
    - 'artJs/utils/Class'
    - 'artJs/events/Delegate'
    - 'artJs/utils/Math'
    - 'artJs/utils/String'
    - 'artJs/utils/Date'
    - 'artJs/utils/Element'
    - 'artJs/utils/Lang'
    - 'artJs/utils/Toggler'
    - 'artJs/utils/ClassToggler' 
    - 'artJs/events/Event'
    - 'artJs/math/Point'
    - 'artJs/math/Rectangle'
    - 'artJs/dom/ElementBuilder'
    - 'artJs/dom/Selector'
    - 'artJs/net/Ajax'
    - 'artJs/net/Router'
    - 'artJs/data/List'
    - 'artJs/data/Queue'
    - 'artJs/events/Channel'
    - 'artJs/events/Clock'
    - 'artJs/events/ElementEvent'
    - 'artJs/events/Timeline'
    - 'artJs/events/Timeout'
    - 'artJs/model/Base'
    - 'artJs/model/ListItem'
    - 'artJs/transition/Base'
    - 'artJs/transition/Blind'
    - 'artJs/transition/Fade'
    - 'artJs/spec/matcher/Base'
    - 'artJs/spec/matcher/A'
    - 'artJs/spec/matcher/Eq'
    - 'artJs/spec/matcher/False'
    - 'artJs/spec/matcher/Null'
    - 'artJs/spec/matcher/Receive'
    - 'artJs/spec/matcher/True'
    - 'artJs/spec/node/Base'
    - 'artJs/spec/node/AutoExec'
    - 'artJs/spec/node/Before'
    - 'artJs/spec/node/Context'
    - 'artJs/spec/node/Describe'
    - 'artJs/spec/node/It'
    - 'artJs/spec/node/Specify'
    - 'artJs/spec/runner/Base'
    - 'artJs/spec/runner/Real'
    - 'artJs/spec/runner/Dry'
    - 'artJs/spec/view/Base'
    - 'artJs/spec/view/Browser'
    - 'artJs/spec/Actual'
    - 'artJs/spec/Api'
    - 'artJs/spec/Mock'
    - 'artJs/spec/Receiver'
    - 'artJs/spec/Result'
    - 'artJs/spec/Spec'
    - 'artJs/template/Base'
    - 'artJs/template/Compiler'
    - 'artJs/template/Helpers'
    - 'artJs/template/Library'
    - 'artJs/utils/component/EventHandler' 
    - 'artJs/utils/component/ListListener' 
    - 'artJs/utils/component/Scanner' 
    - 'artJs/utils/component/Sweeper' 
    - 'artJs/component/Base'
    - 'artJs/component/Button'
    - 'artJs/component/Calendar'
    - 'artJs/component/CheckBox'
    - 'artJs/component/Link'
    - 'artJs/component/Select'
    - 'artJs/component/Table'
    - 'artJs/component/Text'
    - 'artJs/component/Tree'
    - 'artJs/ui/ElementInspector'
    - 'artJs/view/Base'
    - 'artJs/view/Input'
    - 'artJs/view/List'
    - 'artJs/view/DatePicker'
    - 'artJs/view/Template'
    - 'artJs/Shortcuts'
    - 'artJs/Finalize'
  docs-dev: 
    - 'Docs'
    - 'art/Member'
    - 'art/DB'
    - 'art/Helpers'
    - 'art/component/Sidebar'
    - 'art/component/Content'
    - 'art/component/Member'
    - 'art/component/Test'
    - 'art/view/Version'
  main-dev: 'Main'
stylesheets:
  shared-dev: 'css/shared'
  docs-dev: 'css/docs'
  main-dev: 'css/main'
  artjs-dev: 'css/artjs'

